version: "3.8"

services: 
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.dockerfile
            args:
                HOSTNAME: "${HOSTNAME}"
        image: nginx
        ports: 
            - ${MAIN_PORT}:80
        links:
            - fpm
        volumes: 
            - ./app:/var/www/${HOSTNAME}
            - ./docker/xdebug.conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=${HOSTNAME}"


    fpm:
        build:
            context: ./
            dockerfile: docker/fpm.dockerfile
            args:
                HOSTNAME: "${HOSTNAME}"
        volumes: 
            - ./app:/var/www/${HOSTNAME}
            - ./docker/xdebug.conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=${HOSTNAME}"


                
